server:
  port: 80
debug: false

  #db
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/finance
    password: root
    username: root
    type: com.alibaba.druid.pool.DruidDataSource
    InitialSize: 5
    maxWait: 60000
    maxActive: 10
    filters: stat,log4j
  redis:
    port: 6379
    host: 127.0.0.1
#rabbitmq
  rabbitmq:
    addresses: 154.8.226.180
    password: guest
    username: guest

#开启驼峰
mybatis:
  configuration:
    map-underscore-to-camel-case: true

